spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    store-type: REDIS
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 1000s


#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true